name: Deploy via FTP

on:
  push:
    branches:
      - main  # O la rama que quieras desplegar

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ftp://tuservidor.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
